version: '3.5'
services:
  nginx:
    container_name: ${CRAFT_APP_ID}_nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - default
      - proxynet

  php:
    container_name: ${CRAFT_APP_ID}_php
    build: ./docker/app
    volumes:
      - ./:/var/www/html
      - ./docker/app/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]

  db:
    container_name: ${CRAFT_APP_ID}_db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${CRAFT_DB_PASSWORD}
      MYSQL_DATABASE: ${CRAFT_DB_DATABASE}
      MYSQL_USER: ${CRAFT_DB_USER}
      MYSQL_PASSWORD: ${CRAFT_DB_PASSWORD}
      MYSQL_PORT: ${CRAFT_DB_PORT}
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    container_name: ${CRAFT_APP_ID}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8888:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db-data:

networks:
  proxynet:
    name: proxy_network